### ISSUE TITLE
Test-connection -TimeSeconds parameter not recongnized (NamedParameterNotFound)

### ISSUE THREAD

**Issue by boubakeraddy** [ChrisTitusTech/powershell-profile#62] opened 2024-05-05 10:47 UTC
Powershell: version 5

This is the printed error:
Test-Connection : A parameter cannot be found that matches parameter name 'TimeoutSeconds'.
At C:\Users\HP\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:5 char:66
+ ... GitHub = Test-Connection github.com -Count 1 -Quiet -TimeoutSeconds 1
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-Connection], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.TestConnectionCommand

**Comment by todddube** [comment] 2024-05-05 14:09
Having the same issue - thanks for posting

**Comment by dusberendguy** [comment] 2024-05-05 14:43
I have the same issue. please tell me if you find a solution.

**Comment by dusberendguy** [comment] 2024-05-05 14:44
apparently you have to update your powershell

**Comment by todddube** [comment] 2024-05-05 15:28
Yeah - Did that have now font problem... uninstalling

e: ***@***.***
m: 804-432-8850

**Comment by aaronstpierre** [comment] 2024-05-07 16:09
One thing I did find is that blowing away the script and downloading it again and then everything seemed to work!

**Comment by og-mrk** [comment] 2024-05-12 11:45
This's a duplicate of an older issue. the issue is https://github.com/ChrisTitusTech/powershell-profile/issues/48

Nonetheless, thanks to everyone who reported/suggested fixes to this particular issue 😄

**Closed** 2024-06-29 23:15 UTC
