### ISSUE TITLE
Set-Alias : Cannot bind argument to parameter 'Value' because it is null.

### ISSUE THREAD

**Issue by itsRealGray** [ChrisTitusTech/powershell-profile#19] opened 2022-11-28 19:07 UTC
![image](https://user-images.githubusercontent.com/102512869/204359817-4bbb3f7b-99fb-47c4-9641-aa197eb33118.png)
how do i fix this. explain in with monkey mode on please (if its possible😅). i'm not that expert.

**Comment by sahil-jindal** [comment] 2023-01-15 00:50
Hi @itsRealGray, This issue is a duplicate of [Issue 4](https://github.com/ChrisTitusTech/powershell-profile/issues/4). Please checkout the solution proposed in that issue.

**Comment by sahil-jindal** [comment] 2023-01-15 01:42
Hi @itsRealGray, Could you please tell me something about "monkey mode"? Also, Is this the first look after you installed the script?

**Comment by itsRealGray** [comment] 2023-01-18 21:23
> 

thanks man it worked.

**Comment by sahil-jindal** [comment] 2023-01-18 23:58
You're welcome! Now Please close this issue.

**Closed** 2023-01-25 16:06 UTC
